services:
  project_db:
    image: postgres:latest
    container_name: project_db
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
    ports:
      - "6000:5432"
    networks:
      - project_network

  project_pgadmin:
    image: dpage/pgadmin4
    container_name: project_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "9000:80"
    depends_on:
      - project_db
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - project_network

volumes:
  pgadmin_data:

networks:
  project_network:
    external: true
